from enum import Enum


class NotificationStatus(str, Enum):
    RECEIVED = "RECEIVED"
    INITIAL_PROCESSING_FAILURE = "INITIAL_PROCESSING_FAILURE"
    INTERMEDIATE_PROCESSED = "INTERMEDIATE_PROCESSED"
    REPROCESSING_SUCCESS = "REPROCESSING_SUCCESS"
    FINAL_REPROCESS_FAILURE = "FINAL_REPROCESS_FAILURE"
    FINAL_SEND_FAILURE = "FINAL_SEND_FAILURE"
    SENT_SUCCESS = "SENT_SUCCESS"
